// Code generated by the FlatBuffers compiler. DO NOT EDIT.
//
// 来源 schema : https://raw.githubusercontent.com/open-meteo/sdk/main/flatbuffers/weather_api.fbs
// flatc 版本  : 25.12.19
// 生成命令    :
//
//	curl -o weather_api.fbs https://raw.githubusercontent.com/open-meteo/sdk/main/flatbuffers/weather_api.fbs
//	flatc --go --gen-onefile -o internal/api/openmeteo weather_api.fbs
//	# flatc --gen-onefile 会产出空的 `package ` 行（上游 bug），需补成 openmeteo：
//	sed -i '' 's/^package $/package openmeteo/' internal/api/openmeteo/weather_api_generated.go
//
// 为什么把生成物提交进仓库：open-meteo/sdk 仓库只有 csharp/java/kotlin/python/
// swift/ts 绑定，没有 Go 绑定可供 import；而构建机不应依赖本机装有 flatc。
// 生成物是纯 Go、无 CGO，CGO_ENABLED=0 交叉编译无副作用。
//
// 重新生成时请原样保留本注释块。

package openmeteo

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"
)

type Unit byte

const (
	Unitundefined                           Unit = 0
	Unitcelsius                             Unit = 1
	Unitcentimetre                          Unit = 2
	Unitcubic_metre_per_cubic_metre         Unit = 3
	Unitcubic_metre_per_second              Unit = 4
	Unitdegree_direction                    Unit = 5
	Unitdimensionless_integer               Unit = 6
	Unitdimensionless                       Unit = 7
	Uniteuropean_air_quality_index          Unit = 8
	Unitfahrenheit                          Unit = 9
	Unitfeet                                Unit = 10
	Unitfraction                            Unit = 11
	Unitgdd_celsius                         Unit = 12
	Unitgeopotential_metre                  Unit = 13
	Unitgrains_per_cubic_metre              Unit = 14
	Unitgram_per_kilogram                   Unit = 15
	Unithectopascal                         Unit = 16
	Unithours                               Unit = 17
	Unitinch                                Unit = 18
	Unitiso8601                             Unit = 19
	Unitjoule_per_kilogram                  Unit = 20
	Unitkelvin                              Unit = 21
	Unitkilopascal                          Unit = 22
	Unitkilogram_per_square_metre           Unit = 23
	Unitkilometres_per_hour                 Unit = 24
	Unitknots                               Unit = 25
	Unitmegajoule_per_square_metre          Unit = 26
	Unitmetre_per_second_not_unit_converted Unit = 27
	Unitmetre_per_second                    Unit = 28
	Unitmetre                               Unit = 29
	Unitmicrograms_per_cubic_metre          Unit = 30
	Unitmiles_per_hour                      Unit = 31
	Unitmillimetre                          Unit = 32
	Unitpascal                              Unit = 33
	Unitper_second                          Unit = 34
	Unitpercentage                          Unit = 35
	Unitseconds                             Unit = 36
	Unitunix_time                           Unit = 37
	Unitus_air_quality_index                Unit = 38
	Unitwatt_per_square_metre               Unit = 39
	Unitwmo_code                            Unit = 40
	Unitparts_per_million                   Unit = 41
	Unitkilogram_per_cubic_metre            Unit = 42
)

var EnumNamesUnit = map[Unit]string{
	Unitundefined:                           "undefined",
	Unitcelsius:                             "celsius",
	Unitcentimetre:                          "centimetre",
	Unitcubic_metre_per_cubic_metre:         "cubic_metre_per_cubic_metre",
	Unitcubic_metre_per_second:              "cubic_metre_per_second",
	Unitdegree_direction:                    "degree_direction",
	Unitdimensionless_integer:               "dimensionless_integer",
	Unitdimensionless:                       "dimensionless",
	Uniteuropean_air_quality_index:          "european_air_quality_index",
	Unitfahrenheit:                          "fahrenheit",
	Unitfeet:                                "feet",
	Unitfraction:                            "fraction",
	Unitgdd_celsius:                         "gdd_celsius",
	Unitgeopotential_metre:                  "geopotential_metre",
	Unitgrains_per_cubic_metre:              "grains_per_cubic_metre",
	Unitgram_per_kilogram:                   "gram_per_kilogram",
	Unithectopascal:                         "hectopascal",
	Unithours:                               "hours",
	Unitinch:                                "inch",
	Unitiso8601:                             "iso8601",
	Unitjoule_per_kilogram:                  "joule_per_kilogram",
	Unitkelvin:                              "kelvin",
	Unitkilopascal:                          "kilopascal",
	Unitkilogram_per_square_metre:           "kilogram_per_square_metre",
	Unitkilometres_per_hour:                 "kilometres_per_hour",
	Unitknots:                               "knots",
	Unitmegajoule_per_square_metre:          "megajoule_per_square_metre",
	Unitmetre_per_second_not_unit_converted: "metre_per_second_not_unit_converted",
	Unitmetre_per_second:                    "metre_per_second",
	Unitmetre:                               "metre",
	Unitmicrograms_per_cubic_metre:          "micrograms_per_cubic_metre",
	Unitmiles_per_hour:                      "miles_per_hour",
	Unitmillimetre:                          "millimetre",
	Unitpascal:                              "pascal",
	Unitper_second:                          "per_second",
	Unitpercentage:                          "percentage",
	Unitseconds:                             "seconds",
	Unitunix_time:                           "unix_time",
	Unitus_air_quality_index:                "us_air_quality_index",
	Unitwatt_per_square_metre:               "watt_per_square_metre",
	Unitwmo_code:                            "wmo_code",
	Unitparts_per_million:                   "parts_per_million",
	Unitkilogram_per_cubic_metre:            "kilogram_per_cubic_metre",
}

var EnumValuesUnit = map[string]Unit{
	"undefined":                           Unitundefined,
	"celsius":                             Unitcelsius,
	"centimetre":                          Unitcentimetre,
	"cubic_metre_per_cubic_metre":         Unitcubic_metre_per_cubic_metre,
	"cubic_metre_per_second":              Unitcubic_metre_per_second,
	"degree_direction":                    Unitdegree_direction,
	"dimensionless_integer":               Unitdimensionless_integer,
	"dimensionless":                       Unitdimensionless,
	"european_air_quality_index":          Uniteuropean_air_quality_index,
	"fahrenheit":                          Unitfahrenheit,
	"feet":                                Unitfeet,
	"fraction":                            Unitfraction,
	"gdd_celsius":                         Unitgdd_celsius,
	"geopotential_metre":                  Unitgeopotential_metre,
	"grains_per_cubic_metre":              Unitgrains_per_cubic_metre,
	"gram_per_kilogram":                   Unitgram_per_kilogram,
	"hectopascal":                         Unithectopascal,
	"hours":                               Unithours,
	"inch":                                Unitinch,
	"iso8601":                             Unitiso8601,
	"joule_per_kilogram":                  Unitjoule_per_kilogram,
	"kelvin":                              Unitkelvin,
	"kilopascal":                          Unitkilopascal,
	"kilogram_per_square_metre":           Unitkilogram_per_square_metre,
	"kilometres_per_hour":                 Unitkilometres_per_hour,
	"knots":                               Unitknots,
	"megajoule_per_square_metre":          Unitmegajoule_per_square_metre,
	"metre_per_second_not_unit_converted": Unitmetre_per_second_not_unit_converted,
	"metre_per_second":                    Unitmetre_per_second,
	"metre":                               Unitmetre,
	"micrograms_per_cubic_metre":          Unitmicrograms_per_cubic_metre,
	"miles_per_hour":                      Unitmiles_per_hour,
	"millimetre":                          Unitmillimetre,
	"pascal":                              Unitpascal,
	"per_second":                          Unitper_second,
	"percentage":                          Unitpercentage,
	"seconds":                             Unitseconds,
	"unix_time":                           Unitunix_time,
	"us_air_quality_index":                Unitus_air_quality_index,
	"watt_per_square_metre":               Unitwatt_per_square_metre,
	"wmo_code":                            Unitwmo_code,
	"parts_per_million":                   Unitparts_per_million,
	"kilogram_per_cubic_metre":            Unitkilogram_per_cubic_metre,
}

func (v Unit) String() string {
	if s, ok := EnumNamesUnit[v]; ok {
		return s
	}
	return "Unit(" + strconv.FormatInt(int64(v), 10) + ")"
}

type Model byte

const (
	Modelundefined                             Model = 0
	Modelbest_match                            Model = 1
	Modelgfs_seamless                          Model = 2
	Modelgfs_global                            Model = 3
	Modelgfs_hrrr                              Model = 4
	Modelmeteofrance_seamless                  Model = 5
	Modelmeteofrance_arpege_seamless           Model = 6
	Modelmeteofrance_arpege_world              Model = 7
	Modelmeteofrance_arpege_europe             Model = 8
	Modelmeteofrance_arome_seamless            Model = 9
	Modelmeteofrance_arome_france              Model = 10
	Modelmeteofrance_arome_france_hd           Model = 11
	Modeljma_seamless                          Model = 12
	Modeljma_msm                               Model = 13
	Modeljms_gsm                               Model = 14
	Modeljma_gsm                               Model = 15
	Modelgem_seamless                          Model = 16
	Modelgem_global                            Model = 17
	Modelgem_regional                          Model = 18
	Modelgem_hrdps_continental                 Model = 19
	Modelicon_seamless                         Model = 20
	Modelicon_global                           Model = 21
	Modelicon_eu                               Model = 22
	Modelicon_d2                               Model = 23
	Modelecmwf_ifs04                           Model = 24
	Modelmetno_nordic                          Model = 25
	Modelera5_seamless                         Model = 26
	Modelera5                                  Model = 27
	Modelcerra                                 Model = 28
	Modelera5_land                             Model = 29
	Modelecmwf_ifs                             Model = 30
	Modelgwam                                  Model = 31
	Modelewam                                  Model = 32
	Modelglofas_seamless_v3                    Model = 33
	Modelglofas_forecast_v3                    Model = 34
	Modelglofas_consolidated_v3                Model = 35
	Modelglofas_seamless_v4                    Model = 36
	Modelglofas_forecast_v4                    Model = 37
	Modelglofas_consolidated_v4                Model = 38
	Modelgfs025                                Model = 39
	Modelgfs05                                 Model = 40
	ModelCMCC_CM2_VHR4                         Model = 41
	ModelFGOALS_f3_H_highresSST                Model = 42
	ModelFGOALS_f3_H                           Model = 43
	ModelHiRAM_SIT_HR                          Model = 44
	ModelMRI_AGCM3_2_S                         Model = 45
	ModelEC_Earth3P_HR                         Model = 46
	ModelMPI_ESM1_2_XR                         Model = 47
	ModelNICAM16_8S                            Model = 48
	Modelcams_europe                           Model = 49
	Modelcams_global                           Model = 50
	Modelcfsv2                                 Model = 51
	Modelera5_ocean                            Model = 52
	Modelcma_grapes_global                     Model = 53
	Modelbom_access_global                     Model = 54
	Modelbom_access_global_ensemble            Model = 55
	Modelarpae_cosmo_seamless                  Model = 56
	Modelarpae_cosmo_2i                        Model = 57
	Modelarpae_cosmo_2i_ruc                    Model = 58
	Modelarpae_cosmo_5m                        Model = 59
	Modelecmwf_ifs025                          Model = 60
	Modelecmwf_aifs025                         Model = 61
	Modelgfs013                                Model = 62
	Modelgfs_graphcast025                      Model = 63
	Modelecmwf_wam025                          Model = 64
	Modelmeteofrance_wave                      Model = 65
	Modelmeteofrance_currents                  Model = 66
	Modelecmwf_wam025_ensemble                 Model = 67
	Modelncep_gfswave025                       Model = 68
	Modelncep_gefswave025                      Model = 69
	Modelknmi_seamless                         Model = 70
	Modelknmi_harmonie_arome_europe            Model = 71
	Modelknmi_harmonie_arome_netherlands       Model = 72
	Modeldmi_seamless                          Model = 73
	Modeldmi_harmonie_arome_europe             Model = 74
	Modelmetno_seamless                        Model = 75
	Modelera5_ensemble                         Model = 76
	Modelecmwf_ifs_analysis                    Model = 77
	Modelecmwf_ifs_long_window                 Model = 78
	Modelecmwf_ifs_analysis_long_window        Model = 79
	Modelukmo_global_deterministic_10km        Model = 80
	Modelukmo_uk_deterministic_2km             Model = 81
	Modelukmo_seamless                         Model = 82
	Modelncep_gfswave016                       Model = 83
	Modelncep_nbm_conus                        Model = 84
	Modelukmo_global_ensemble_20km             Model = 85
	Modelecmwf_aifs025_single                  Model = 86
	Modeljma_jaxa_himawari                     Model = 87
	Modeleumetsat_sarah3                       Model = 88
	Modeleumetsat_lsa_saf_msg                  Model = 89
	Modeleumetsat_lsa_saf_iodc                 Model = 90
	Modelsatellite_radiation_seamless          Model = 91
	Modelkma_gdps                              Model = 92
	Modelkma_ldps                              Model = 93
	Modelkma_seamless                          Model = 94
	Modelitalia_meteo_arpae_icon_2i            Model = 95
	Modelukmo_uk_ensemble_2km                  Model = 96
	Modelmeteofrance_arome_france_hd_15min     Model = 97
	Modelmeteofrance_arome_france_15min        Model = 98
	Modelmeteoswiss_icon_ch1                   Model = 99
	Modelmeteoswiss_icon_ch2                   Model = 100
	Modelmeteoswiss_icon_ch1_ensemble          Model = 101
	Modelmeteoswiss_icon_ch2_ensemble          Model = 102
	Modelmeteoswiss_icon_seamless              Model = 103
	Modelncep_nam_conus                        Model = 104
	Modelicon_d2_ruc                           Model = 105
	Modelecmwf_seas5                           Model = 106
	Modelecmwf_ec46                            Model = 107
	Modelecmwf_seasonal_seamless               Model = 108
	Modelecmwf_ifs_seamless                    Model = 109
	Modeljma_jaxa_mtg_fci                      Model = 110
	Modelgem_hrdps_west                        Model = 111
	Modelecmwf_wam                             Model = 112
	Modelncep_aigfs025                         Model = 113
	Modelncep_aigefs025                        Model = 114
	Modelncep_hgefs025_ensemble_mean           Model = 115
	Modelecmwf_seasonal_ensemble_mean_seamless Model = 116
	Modelecmwf_seas5_ensemble_mean             Model = 117
	Modelecmwf_ec46_ensemble_mean              Model = 118
	Modelncep_aigefs025_ensemble_mean          Model = 119
	Modeldwd_icon_eps_ensemble_mean_seamless   Model = 120
	Modeldwd_icon_eps_ensemble_mean            Model = 121
	Modeldwd_icon_eu_eps_ensemble_mean         Model = 122
	Modeldwd_icon_d2_eps_ensemble_mean         Model = 123
	Modelncep_gefs_ensemble_mean_seamless      Model = 124
	Modelncep_gefs025_ensemble_mean            Model = 125
	Modelncep_gefs05_ensemble_mean             Model = 126
	Modelecmwf_ifs025_ensemble_mean            Model = 127
	Modelecmwf_aifs025_ensemble_mean           Model = 128
	Modelmeteoswiss_icon_ch1_ensemble_mean     Model = 129
	Modelmeteoswiss_icon_ch2_ensemble_mean     Model = 130
	Modelcmc_gem_geps_ensemble_mean            Model = 131
	Modelukmo_global_ensemble_mean_20km        Model = 132
	Modelukmo_uk_ensemble_mean_2km             Model = 133
	Modeldwd_sis_europe_africa_v4              Model = 134
	Modelbom_access_global_ensemble_mean       Model = 135
	Modelecmwf_wam025_ensemble_mean            Model = 136
	Modelncep_gefswave025_ensemble_mean        Model = 137
	Modelgeosphere_arome_austria               Model = 138
	Modelgeosphere_seamless                    Model = 139
	Modelchmi_aladin_cz_1km                    Model = 140
	Modelecmwf_ifs_europe_ensemble             Model = 141
	Modelecmwf_ifs_europe_ensemble_mean        Model = 142
	Modelecmwf_aifs_europe_ensemble            Model = 143
	Modelecmwf_aifs_europe_ensemble_mean       Model = 144
	Modelgoogle_weathernext2_ensemble          Model = 145
	Modelgoogle_weathernext2_ensemble_mean     Model = 146
)

var EnumNamesModel = map[Model]string{
	Modelundefined:                             "undefined",
	Modelbest_match:                            "best_match",
	Modelgfs_seamless:                          "gfs_seamless",
	Modelgfs_global:                            "gfs_global",
	Modelgfs_hrrr:                              "gfs_hrrr",
	Modelmeteofrance_seamless:                  "meteofrance_seamless",
	Modelmeteofrance_arpege_seamless:           "meteofrance_arpege_seamless",
	Modelmeteofrance_arpege_world:              "meteofrance_arpege_world",
	Modelmeteofrance_arpege_europe:             "meteofrance_arpege_europe",
	Modelmeteofrance_arome_seamless:            "meteofrance_arome_seamless",
	Modelmeteofrance_arome_france:              "meteofrance_arome_france",
	Modelmeteofrance_arome_france_hd:           "meteofrance_arome_france_hd",
	Modeljma_seamless:                          "jma_seamless",
	Modeljma_msm:                               "jma_msm",
	Modeljms_gsm:                               "jms_gsm",
	Modeljma_gsm:                               "jma_gsm",
	Modelgem_seamless:                          "gem_seamless",
	Modelgem_global:                            "gem_global",
	Modelgem_regional:                          "gem_regional",
	Modelgem_hrdps_continental:                 "gem_hrdps_continental",
	Modelicon_seamless:                         "icon_seamless",
	Modelicon_global:                           "icon_global",
	Modelicon_eu:                               "icon_eu",
	Modelicon_d2:                               "icon_d2",
	Modelecmwf_ifs04:                           "ecmwf_ifs04",
	Modelmetno_nordic:                          "metno_nordic",
	Modelera5_seamless:                         "era5_seamless",
	Modelera5:                                  "era5",
	Modelcerra:                                 "cerra",
	Modelera5_land:                             "era5_land",
	Modelecmwf_ifs:                             "ecmwf_ifs",
	Modelgwam:                                  "gwam",
	Modelewam:                                  "ewam",
	Modelglofas_seamless_v3:                    "glofas_seamless_v3",
	Modelglofas_forecast_v3:                    "glofas_forecast_v3",
	Modelglofas_consolidated_v3:                "glofas_consolidated_v3",
	Modelglofas_seamless_v4:                    "glofas_seamless_v4",
	Modelglofas_forecast_v4:                    "glofas_forecast_v4",
	Modelglofas_consolidated_v4:                "glofas_consolidated_v4",
	Modelgfs025:                                "gfs025",
	Modelgfs05:                                 "gfs05",
	ModelCMCC_CM2_VHR4:                         "CMCC_CM2_VHR4",
	ModelFGOALS_f3_H_highresSST:                "FGOALS_f3_H_highresSST",
	ModelFGOALS_f3_H:                           "FGOALS_f3_H",
	ModelHiRAM_SIT_HR:                          "HiRAM_SIT_HR",
	ModelMRI_AGCM3_2_S:                         "MRI_AGCM3_2_S",
	ModelEC_Earth3P_HR:                         "EC_Earth3P_HR",
	ModelMPI_ESM1_2_XR:                         "MPI_ESM1_2_XR",
	ModelNICAM16_8S:                            "NICAM16_8S",
	Modelcams_europe:                           "cams_europe",
	Modelcams_global:                           "cams_global",
	Modelcfsv2:                                 "cfsv2",
	Modelera5_ocean:                            "era5_ocean",
	Modelcma_grapes_global:                     "cma_grapes_global",
	Modelbom_access_global:                     "bom_access_global",
	Modelbom_access_global_ensemble:            "bom_access_global_ensemble",
	Modelarpae_cosmo_seamless:                  "arpae_cosmo_seamless",
	Modelarpae_cosmo_2i:                        "arpae_cosmo_2i",
	Modelarpae_cosmo_2i_ruc:                    "arpae_cosmo_2i_ruc",
	Modelarpae_cosmo_5m:                        "arpae_cosmo_5m",
	Modelecmwf_ifs025:                          "ecmwf_ifs025",
	Modelecmwf_aifs025:                         "ecmwf_aifs025",
	Modelgfs013:                                "gfs013",
	Modelgfs_graphcast025:                      "gfs_graphcast025",
	Modelecmwf_wam025:                          "ecmwf_wam025",
	Modelmeteofrance_wave:                      "meteofrance_wave",
	Modelmeteofrance_currents:                  "meteofrance_currents",
	Modelecmwf_wam025_ensemble:                 "ecmwf_wam025_ensemble",
	Modelncep_gfswave025:                       "ncep_gfswave025",
	Modelncep_gefswave025:                      "ncep_gefswave025",
	Modelknmi_seamless:                         "knmi_seamless",
	Modelknmi_harmonie_arome_europe:            "knmi_harmonie_arome_europe",
	Modelknmi_harmonie_arome_netherlands:       "knmi_harmonie_arome_netherlands",
	Modeldmi_seamless:                          "dmi_seamless",
	Modeldmi_harmonie_arome_europe:             "dmi_harmonie_arome_europe",
	Modelmetno_seamless:                        "metno_seamless",
	Modelera5_ensemble:                         "era5_ensemble",
	Modelecmwf_ifs_analysis:                    "ecmwf_ifs_analysis",
	Modelecmwf_ifs_long_window:                 "ecmwf_ifs_long_window",
	Modelecmwf_ifs_analysis_long_window:        "ecmwf_ifs_analysis_long_window",
	Modelukmo_global_deterministic_10km:        "ukmo_global_deterministic_10km",
	Modelukmo_uk_deterministic_2km:             "ukmo_uk_deterministic_2km",
	Modelukmo_seamless:                         "ukmo_seamless",
	Modelncep_gfswave016:                       "ncep_gfswave016",
	Modelncep_nbm_conus:                        "ncep_nbm_conus",
	Modelukmo_global_ensemble_20km:             "ukmo_global_ensemble_20km",
	Modelecmwf_aifs025_single:                  "ecmwf_aifs025_single",
	Modeljma_jaxa_himawari:                     "jma_jaxa_himawari",
	Modeleumetsat_sarah3:                       "eumetsat_sarah3",
	Modeleumetsat_lsa_saf_msg:                  "eumetsat_lsa_saf_msg",
	Modeleumetsat_lsa_saf_iodc:                 "eumetsat_lsa_saf_iodc",
	Modelsatellite_radiation_seamless:          "satellite_radiation_seamless",
	Modelkma_gdps:                              "kma_gdps",
	Modelkma_ldps:                              "kma_ldps",
	Modelkma_seamless:                          "kma_seamless",
	Modelitalia_meteo_arpae_icon_2i:            "italia_meteo_arpae_icon_2i",
	Modelukmo_uk_ensemble_2km:                  "ukmo_uk_ensemble_2km",
	Modelmeteofrance_arome_france_hd_15min:     "meteofrance_arome_france_hd_15min",
	Modelmeteofrance_arome_france_15min:        "meteofrance_arome_france_15min",
	Modelmeteoswiss_icon_ch1:                   "meteoswiss_icon_ch1",
	Modelmeteoswiss_icon_ch2:                   "meteoswiss_icon_ch2",
	Modelmeteoswiss_icon_ch1_ensemble:          "meteoswiss_icon_ch1_ensemble",
	Modelmeteoswiss_icon_ch2_ensemble:          "meteoswiss_icon_ch2_ensemble",
	Modelmeteoswiss_icon_seamless:              "meteoswiss_icon_seamless",
	Modelncep_nam_conus:                        "ncep_nam_conus",
	Modelicon_d2_ruc:                           "icon_d2_ruc",
	Modelecmwf_seas5:                           "ecmwf_seas5",
	Modelecmwf_ec46:                            "ecmwf_ec46",
	Modelecmwf_seasonal_seamless:               "ecmwf_seasonal_seamless",
	Modelecmwf_ifs_seamless:                    "ecmwf_ifs_seamless",
	Modeljma_jaxa_mtg_fci:                      "jma_jaxa_mtg_fci",
	Modelgem_hrdps_west:                        "gem_hrdps_west",
	Modelecmwf_wam:                             "ecmwf_wam",
	Modelncep_aigfs025:                         "ncep_aigfs025",
	Modelncep_aigefs025:                        "ncep_aigefs025",
	Modelncep_hgefs025_ensemble_mean:           "ncep_hgefs025_ensemble_mean",
	Modelecmwf_seasonal_ensemble_mean_seamless: "ecmwf_seasonal_ensemble_mean_seamless",
	Modelecmwf_seas5_ensemble_mean:             "ecmwf_seas5_ensemble_mean",
	Modelecmwf_ec46_ensemble_mean:              "ecmwf_ec46_ensemble_mean",
	Modelncep_aigefs025_ensemble_mean:          "ncep_aigefs025_ensemble_mean",
	Modeldwd_icon_eps_ensemble_mean_seamless:   "dwd_icon_eps_ensemble_mean_seamless",
	Modeldwd_icon_eps_ensemble_mean:            "dwd_icon_eps_ensemble_mean",
	Modeldwd_icon_eu_eps_ensemble_mean:         "dwd_icon_eu_eps_ensemble_mean",
	Modeldwd_icon_d2_eps_ensemble_mean:         "dwd_icon_d2_eps_ensemble_mean",
	Modelncep_gefs_ensemble_mean_seamless:      "ncep_gefs_ensemble_mean_seamless",
	Modelncep_gefs025_ensemble_mean:            "ncep_gefs025_ensemble_mean",
	Modelncep_gefs05_ensemble_mean:             "ncep_gefs05_ensemble_mean",
	Modelecmwf_ifs025_ensemble_mean:            "ecmwf_ifs025_ensemble_mean",
	Modelecmwf_aifs025_ensemble_mean:           "ecmwf_aifs025_ensemble_mean",
	Modelmeteoswiss_icon_ch1_ensemble_mean:     "meteoswiss_icon_ch1_ensemble_mean",
	Modelmeteoswiss_icon_ch2_ensemble_mean:     "meteoswiss_icon_ch2_ensemble_mean",
	Modelcmc_gem_geps_ensemble_mean:            "cmc_gem_geps_ensemble_mean",
	Modelukmo_global_ensemble_mean_20km:        "ukmo_global_ensemble_mean_20km",
	Modelukmo_uk_ensemble_mean_2km:             "ukmo_uk_ensemble_mean_2km",
	Modeldwd_sis_europe_africa_v4:              "dwd_sis_europe_africa_v4",
	Modelbom_access_global_ensemble_mean:       "bom_access_global_ensemble_mean",
	Modelecmwf_wam025_ensemble_mean:            "ecmwf_wam025_ensemble_mean",
	Modelncep_gefswave025_ensemble_mean:        "ncep_gefswave025_ensemble_mean",
	Modelgeosphere_arome_austria:               "geosphere_arome_austria",
	Modelgeosphere_seamless:                    "geosphere_seamless",
	Modelchmi_aladin_cz_1km:                    "chmi_aladin_cz_1km",
	Modelecmwf_ifs_europe_ensemble:             "ecmwf_ifs_europe_ensemble",
	Modelecmwf_ifs_europe_ensemble_mean:        "ecmwf_ifs_europe_ensemble_mean",
	Modelecmwf_aifs_europe_ensemble:            "ecmwf_aifs_europe_ensemble",
	Modelecmwf_aifs_europe_ensemble_mean:       "ecmwf_aifs_europe_ensemble_mean",
	Modelgoogle_weathernext2_ensemble:          "google_weathernext2_ensemble",
	Modelgoogle_weathernext2_ensemble_mean:     "google_weathernext2_ensemble_mean",
}

var EnumValuesModel = map[string]Model{
	"undefined":                             Modelundefined,
	"best_match":                            Modelbest_match,
	"gfs_seamless":                          Modelgfs_seamless,
	"gfs_global":                            Modelgfs_global,
	"gfs_hrrr":                              Modelgfs_hrrr,
	"meteofrance_seamless":                  Modelmeteofrance_seamless,
	"meteofrance_arpege_seamless":           Modelmeteofrance_arpege_seamless,
	"meteofrance_arpege_world":              Modelmeteofrance_arpege_world,
	"meteofrance_arpege_europe":             Modelmeteofrance_arpege_europe,
	"meteofrance_arome_seamless":            Modelmeteofrance_arome_seamless,
	"meteofrance_arome_france":              Modelmeteofrance_arome_france,
	"meteofrance_arome_france_hd":           Modelmeteofrance_arome_france_hd,
	"jma_seamless":                          Modeljma_seamless,
	"jma_msm":                               Modeljma_msm,
	"jms_gsm":                               Modeljms_gsm,
	"jma_gsm":                               Modeljma_gsm,
	"gem_seamless":                          Modelgem_seamless,
	"gem_global":                            Modelgem_global,
	"gem_regional":                          Modelgem_regional,
	"gem_hrdps_continental":                 Modelgem_hrdps_continental,
	"icon_seamless":                         Modelicon_seamless,
	"icon_global":                           Modelicon_global,
	"icon_eu":                               Modelicon_eu,
	"icon_d2":                               Modelicon_d2,
	"ecmwf_ifs04":                           Modelecmwf_ifs04,
	"metno_nordic":                          Modelmetno_nordic,
	"era5_seamless":                         Modelera5_seamless,
	"era5":                                  Modelera5,
	"cerra":                                 Modelcerra,
	"era5_land":                             Modelera5_land,
	"ecmwf_ifs":                             Modelecmwf_ifs,
	"gwam":                                  Modelgwam,
	"ewam":                                  Modelewam,
	"glofas_seamless_v3":                    Modelglofas_seamless_v3,
	"glofas_forecast_v3":                    Modelglofas_forecast_v3,
	"glofas_consolidated_v3":                Modelglofas_consolidated_v3,
	"glofas_seamless_v4":                    Modelglofas_seamless_v4,
	"glofas_forecast_v4":                    Modelglofas_forecast_v4,
	"glofas_consolidated_v4":                Modelglofas_consolidated_v4,
	"gfs025":                                Modelgfs025,
	"gfs05":                                 Modelgfs05,
	"CMCC_CM2_VHR4":                         ModelCMCC_CM2_VHR4,
	"FGOALS_f3_H_highresSST":                ModelFGOALS_f3_H_highresSST,
	"FGOALS_f3_H":                           ModelFGOALS_f3_H,
	"HiRAM_SIT_HR":                          ModelHiRAM_SIT_HR,
	"MRI_AGCM3_2_S":                         ModelMRI_AGCM3_2_S,
	"EC_Earth3P_HR":                         ModelEC_Earth3P_HR,
	"MPI_ESM1_2_XR":                         ModelMPI_ESM1_2_XR,
	"NICAM16_8S":                            ModelNICAM16_8S,
	"cams_europe":                           Modelcams_europe,
	"cams_global":                           Modelcams_global,
	"cfsv2":                                 Modelcfsv2,
	"era5_ocean":                            Modelera5_ocean,
	"cma_grapes_global":                     Modelcma_grapes_global,
	"bom_access_global":                     Modelbom_access_global,
	"bom_access_global_ensemble":            Modelbom_access_global_ensemble,
	"arpae_cosmo_seamless":                  Modelarpae_cosmo_seamless,
	"arpae_cosmo_2i":                        Modelarpae_cosmo_2i,
	"arpae_cosmo_2i_ruc":                    Modelarpae_cosmo_2i_ruc,
	"arpae_cosmo_5m":                        Modelarpae_cosmo_5m,
	"ecmwf_ifs025":                          Modelecmwf_ifs025,
	"ecmwf_aifs025":                         Modelecmwf_aifs025,
	"gfs013":                                Modelgfs013,
	"gfs_graphcast025":                      Modelgfs_graphcast025,
	"ecmwf_wam025":                          Modelecmwf_wam025,
	"meteofrance_wave":                      Modelmeteofrance_wave,
	"meteofrance_currents":                  Modelmeteofrance_currents,
	"ecmwf_wam025_ensemble":                 Modelecmwf_wam025_ensemble,
	"ncep_gfswave025":                       Modelncep_gfswave025,
	"ncep_gefswave025":                      Modelncep_gefswave025,
	"knmi_seamless":                         Modelknmi_seamless,
	"knmi_harmonie_arome_europe":            Modelknmi_harmonie_arome_europe,
	"knmi_harmonie_arome_netherlands":       Modelknmi_harmonie_arome_netherlands,
	"dmi_seamless":                          Modeldmi_seamless,
	"dmi_harmonie_arome_europe":             Modeldmi_harmonie_arome_europe,
	"metno_seamless":                        Modelmetno_seamless,
	"era5_ensemble":                         Modelera5_ensemble,
	"ecmwf_ifs_analysis":                    Modelecmwf_ifs_analysis,
	"ecmwf_ifs_long_window":                 Modelecmwf_ifs_long_window,
	"ecmwf_ifs_analysis_long_window":        Modelecmwf_ifs_analysis_long_window,
	"ukmo_global_deterministic_10km":        Modelukmo_global_deterministic_10km,
	"ukmo_uk_deterministic_2km":             Modelukmo_uk_deterministic_2km,
	"ukmo_seamless":                         Modelukmo_seamless,
	"ncep_gfswave016":                       Modelncep_gfswave016,
	"ncep_nbm_conus":                        Modelncep_nbm_conus,
	"ukmo_global_ensemble_20km":             Modelukmo_global_ensemble_20km,
	"ecmwf_aifs025_single":                  Modelecmwf_aifs025_single,
	"jma_jaxa_himawari":                     Modeljma_jaxa_himawari,
	"eumetsat_sarah3":                       Modeleumetsat_sarah3,
	"eumetsat_lsa_saf_msg":                  Modeleumetsat_lsa_saf_msg,
	"eumetsat_lsa_saf_iodc":                 Modeleumetsat_lsa_saf_iodc,
	"satellite_radiation_seamless":          Modelsatellite_radiation_seamless,
	"kma_gdps":                              Modelkma_gdps,
	"kma_ldps":                              Modelkma_ldps,
	"kma_seamless":                          Modelkma_seamless,
	"italia_meteo_arpae_icon_2i":            Modelitalia_meteo_arpae_icon_2i,
	"ukmo_uk_ensemble_2km":                  Modelukmo_uk_ensemble_2km,
	"meteofrance_arome_france_hd_15min":     Modelmeteofrance_arome_france_hd_15min,
	"meteofrance_arome_france_15min":        Modelmeteofrance_arome_france_15min,
	"meteoswiss_icon_ch1":                   Modelmeteoswiss_icon_ch1,
	"meteoswiss_icon_ch2":                   Modelmeteoswiss_icon_ch2,
	"meteoswiss_icon_ch1_ensemble":          Modelmeteoswiss_icon_ch1_ensemble,
	"meteoswiss_icon_ch2_ensemble":          Modelmeteoswiss_icon_ch2_ensemble,
	"meteoswiss_icon_seamless":              Modelmeteoswiss_icon_seamless,
	"ncep_nam_conus":                        Modelncep_nam_conus,
	"icon_d2_ruc":                           Modelicon_d2_ruc,
	"ecmwf_seas5":                           Modelecmwf_seas5,
	"ecmwf_ec46":                            Modelecmwf_ec46,
	"ecmwf_seasonal_seamless":               Modelecmwf_seasonal_seamless,
	"ecmwf_ifs_seamless":                    Modelecmwf_ifs_seamless,
	"jma_jaxa_mtg_fci":                      Modeljma_jaxa_mtg_fci,
	"gem_hrdps_west":                        Modelgem_hrdps_west,
	"ecmwf_wam":                             Modelecmwf_wam,
	"ncep_aigfs025":                         Modelncep_aigfs025,
	"ncep_aigefs025":                        Modelncep_aigefs025,
	"ncep_hgefs025_ensemble_mean":           Modelncep_hgefs025_ensemble_mean,
	"ecmwf_seasonal_ensemble_mean_seamless": Modelecmwf_seasonal_ensemble_mean_seamless,
	"ecmwf_seas5_ensemble_mean":             Modelecmwf_seas5_ensemble_mean,
	"ecmwf_ec46_ensemble_mean":              Modelecmwf_ec46_ensemble_mean,
	"ncep_aigefs025_ensemble_mean":          Modelncep_aigefs025_ensemble_mean,
	"dwd_icon_eps_ensemble_mean_seamless":   Modeldwd_icon_eps_ensemble_mean_seamless,
	"dwd_icon_eps_ensemble_mean":            Modeldwd_icon_eps_ensemble_mean,
	"dwd_icon_eu_eps_ensemble_mean":         Modeldwd_icon_eu_eps_ensemble_mean,
	"dwd_icon_d2_eps_ensemble_mean":         Modeldwd_icon_d2_eps_ensemble_mean,
	"ncep_gefs_ensemble_mean_seamless":      Modelncep_gefs_ensemble_mean_seamless,
	"ncep_gefs025_ensemble_mean":            Modelncep_gefs025_ensemble_mean,
	"ncep_gefs05_ensemble_mean":             Modelncep_gefs05_ensemble_mean,
	"ecmwf_ifs025_ensemble_mean":            Modelecmwf_ifs025_ensemble_mean,
	"ecmwf_aifs025_ensemble_mean":           Modelecmwf_aifs025_ensemble_mean,
	"meteoswiss_icon_ch1_ensemble_mean":     Modelmeteoswiss_icon_ch1_ensemble_mean,
	"meteoswiss_icon_ch2_ensemble_mean":     Modelmeteoswiss_icon_ch2_ensemble_mean,
	"cmc_gem_geps_ensemble_mean":            Modelcmc_gem_geps_ensemble_mean,
	"ukmo_global_ensemble_mean_20km":        Modelukmo_global_ensemble_mean_20km,
	"ukmo_uk_ensemble_mean_2km":             Modelukmo_uk_ensemble_mean_2km,
	"dwd_sis_europe_africa_v4":              Modeldwd_sis_europe_africa_v4,
	"bom_access_global_ensemble_mean":       Modelbom_access_global_ensemble_mean,
	"ecmwf_wam025_ensemble_mean":            Modelecmwf_wam025_ensemble_mean,
	"ncep_gefswave025_ensemble_mean":        Modelncep_gefswave025_ensemble_mean,
	"geosphere_arome_austria":               Modelgeosphere_arome_austria,
	"geosphere_seamless":                    Modelgeosphere_seamless,
	"chmi_aladin_cz_1km":                    Modelchmi_aladin_cz_1km,
	"ecmwf_ifs_europe_ensemble":             Modelecmwf_ifs_europe_ensemble,
	"ecmwf_ifs_europe_ensemble_mean":        Modelecmwf_ifs_europe_ensemble_mean,
	"ecmwf_aifs_europe_ensemble":            Modelecmwf_aifs_europe_ensemble,
	"ecmwf_aifs_europe_ensemble_mean":       Modelecmwf_aifs_europe_ensemble_mean,
	"google_weathernext2_ensemble":          Modelgoogle_weathernext2_ensemble,
	"google_weathernext2_ensemble_mean":     Modelgoogle_weathernext2_ensemble_mean,
}

func (v Model) String() string {
	if s, ok := EnumNamesModel[v]; ok {
		return s
	}
	return "Model(" + strconv.FormatInt(int64(v), 10) + ")"
}

type Variable byte

const (
	Variableundefined                              Variable = 0
	Variableapparent_temperature                   Variable = 1
	Variablecape                                   Variable = 2
	Variablecloud_cover                            Variable = 3
	Variablecloud_cover_high                       Variable = 4
	Variablecloud_cover_low                        Variable = 5
	Variablecloud_cover_mid                        Variable = 6
	Variabledaylight_duration                      Variable = 7
	Variabledew_point                              Variable = 8
	Variablediffuse_radiation                      Variable = 9
	Variablediffuse_radiation_instant              Variable = 10
	Variabledirect_normal_irradiance               Variable = 11
	Variabledirect_normal_irradiance_instant       Variable = 12
	Variabledirect_radiation                       Variable = 13
	Variabledirect_radiation_instant               Variable = 14
	Variableet0_fao_evapotranspiration             Variable = 15
	Variableevapotranspiration                     Variable = 16
	Variablefreezing_level_height                  Variable = 17
	Variablegrowing_degree_days                    Variable = 18
	Variableis_day                                 Variable = 19
	Variablelatent_heat_flux                       Variable = 20
	Variableleaf_wetness_probability               Variable = 21
	Variablelifted_index                           Variable = 22
	Variablelightning_potential                    Variable = 23
	Variableprecipitation                          Variable = 24
	Variableprecipitation_hours                    Variable = 25
	Variableprecipitation_probability              Variable = 26
	Variablepressure_msl                           Variable = 27
	Variablerain                                   Variable = 28
	Variablerelative_humidity                      Variable = 29
	Variablerunoff                                 Variable = 30
	Variablesensible_heat_flux                     Variable = 31
	Variableshortwave_radiation                    Variable = 32
	Variableshortwave_radiation_instant            Variable = 33
	Variableshowers                                Variable = 34
	Variablesnow_depth                             Variable = 35
	Variablesnow_height                            Variable = 36
	Variablesnowfall                               Variable = 37
	Variablesnowfall_height                        Variable = 38
	Variablesnowfall_water_equivalent              Variable = 39
	Variablesunrise                                Variable = 40
	Variablesunset                                 Variable = 41
	Variablesoil_moisture                          Variable = 42
	Variablesoil_moisture_index                    Variable = 43
	Variablesoil_temperature                       Variable = 44
	Variablesurface_pressure                       Variable = 45
	Variablesurface_temperature                    Variable = 46
	Variabletemperature                            Variable = 47
	Variableterrestrial_radiation                  Variable = 48
	Variableterrestrial_radiation_instant          Variable = 49
	Variabletotal_column_integrated_water_vapour   Variable = 50
	Variableupdraft                                Variable = 51
	Variableuv_index                               Variable = 52
	Variableuv_index_clear_sky                     Variable = 53
	Variablevapour_pressure_deficit                Variable = 54
	Variablevisibility                             Variable = 55
	Variableweather_code                           Variable = 56
	Variablewind_direction                         Variable = 57
	Variablewind_gusts                             Variable = 58
	Variablewind_speed                             Variable = 59
	Variablevertical_velocity                      Variable = 60
	Variablegeopotential_height                    Variable = 61
	Variablewet_bulb_temperature                   Variable = 62
	Variableriver_discharge                        Variable = 63
	Variablewave_height                            Variable = 64
	Variablewave_period                            Variable = 65
	Variablewave_direction                         Variable = 66
	Variablewind_wave_height                       Variable = 67
	Variablewind_wave_period                       Variable = 68
	Variablewind_wave_peak_period                  Variable = 69
	Variablewind_wave_direction                    Variable = 70
	Variableswell_wave_height                      Variable = 71
	Variableswell_wave_period                      Variable = 72
	Variableswell_wave_peak_period                 Variable = 73
	Variableswell_wave_direction                   Variable = 74
	Variablepm10                                   Variable = 75
	Variablepm2p5                                  Variable = 76
	Variabledust                                   Variable = 77
	Variableaerosol_optical_depth                  Variable = 78
	Variablecarbon_monoxide                        Variable = 79
	Variablenitrogen_dioxide                       Variable = 80
	Variableammonia                                Variable = 81
	Variableozone                                  Variable = 82
	Variablesulphur_dioxide                        Variable = 83
	Variablealder_pollen                           Variable = 84
	Variablebirch_pollen                           Variable = 85
	Variablegrass_pollen                           Variable = 86
	Variablemugwort_pollen                         Variable = 87
	Variableolive_pollen                           Variable = 88
	Variableragweed_pollen                         Variable = 89
	Variableeuropean_aqi                           Variable = 90
	Variableeuropean_aqi_pm2p5                     Variable = 91
	Variableeuropean_aqi_pm10                      Variable = 92
	Variableeuropean_aqi_nitrogen_dioxide          Variable = 93
	Variableeuropean_aqi_ozone                     Variable = 94
	Variableeuropean_aqi_sulphur_dioxide           Variable = 95
	Variableus_aqi                                 Variable = 96
	Variableus_aqi_pm2p5                           Variable = 97
	Variableus_aqi_pm10                            Variable = 98
	Variableus_aqi_nitrogen_dioxide                Variable = 99
	Variableus_aqi_ozone                           Variable = 100
	Variableus_aqi_sulphur_dioxide                 Variable = 101
	Variableus_aqi_carbon_monoxide                 Variable = 102
	Variablesunshine_duration                      Variable = 103
	Variableconvective_inhibition                  Variable = 104
	Variableshortwave_radiation_clear_sky          Variable = 105
	Variableglobal_tilted_irradiance               Variable = 106
	Variableglobal_tilted_irradiance_instant       Variable = 107
	Variableocean_current_velocity                 Variable = 108
	Variableocean_current_direction                Variable = 109
	Variablecloud_base                             Variable = 110
	Variablecloud_top                              Variable = 111
	Variablemass_density                           Variable = 112
	Variableboundary_layer_height                  Variable = 113
	Variableformaldehyde                           Variable = 114
	Variableglyoxal                                Variable = 115
	Variablenon_methane_volatile_organic_compounds Variable = 116
	Variablepm10_wildfires                         Variable = 117
	Variableperoxyacyl_nitrates                    Variable = 118
	Variablesecondary_inorganic_aerosol            Variable = 119
	Variableresidential_elementary_carbon          Variable = 120
	Variabletotal_elementary_carbon                Variable = 121
	Variablepm2_5_total_organic_matter             Variable = 122
	Variablesea_salt_aerosol                       Variable = 123
	Variablenitrogen_monoxide                      Variable = 124
	Variablethunderstorm_probability               Variable = 125
	Variablerain_probability                       Variable = 126
	Variablefreezing_rain_probability              Variable = 127
	Variableice_pellets_probability                Variable = 128
	Variablesnowfall_probability                   Variable = 129
	Variablecarbon_dioxide                         Variable = 130
	Variablemethane                                Variable = 131
	Variablesea_level_height_msl                   Variable = 132
	Variablesea_surface_temperature                Variable = 133
	Variableinvert_barometer_height                Variable = 134
	Variablehail                                   Variable = 135
	Variablealbedo                                 Variable = 136
	Variableprecipitation_type                     Variable = 137
	Variableconvective_cloud_base                  Variable = 138
	Variableconvective_cloud_top                   Variable = 139
	Variablesnow_depth_water_equivalent            Variable = 140
	Variablesecondary_swell_wave_height            Variable = 141
	Variablesecondary_swell_wave_period            Variable = 142
	Variablesecondary_swell_wave_peak_period       Variable = 143
	Variablesecondary_swell_wave_direction         Variable = 144
	Variabletertiary_swell_wave_height             Variable = 145
	Variabletertiary_swell_wave_period             Variable = 146
	Variabletertiary_swell_wave_peak_period        Variable = 147
	Variabletertiary_swell_wave_direction          Variable = 148
	Variablewind_u_component                       Variable = 149
	Variablewind_v_component                       Variable = 150
	Variabletemperature_max24h                     Variable = 151
	Variabletemperature_min24h                     Variable = 152
	Variabletemperature_mean24h                    Variable = 153
	Variablesnow_density                           Variable = 154
	Variablelongwave_radiation                     Variable = 155
	Variablesea_ice_cover                          Variable = 156
	Variablek_index                                Variable = 157
	Variableroughness_length                       Variable = 158
	Variablepotential_evapotranspiration           Variable = 159
	Variablewave_peak_period                       Variable = 160
	Variabletemperature_max6h                      Variable = 161
	Variabletemperature_min6h                      Variable = 162
	Variablelightning_density                      Variable = 163
	Variablesea_ice_thickness                      Variable = 164
	Variableshortwave_radiation_clear_sky_instant  Variable = 165
	Variablesea_water_salinity                     Variable = 166
	Variabletotal_column_water                     Variable = 167
	Variableair_density                            Variable = 168
	Variablemoonrise                               Variable = 169
	Variablemoonset                                Variable = 170
	Variablemoon_phase                             Variable = 171
)

var EnumNamesVariable = map[Variable]string{
	Variableundefined:                              "undefined",
	Variableapparent_temperature:                   "apparent_temperature",
	Variablecape:                                   "cape",
	Variablecloud_cover:                            "cloud_cover",
	Variablecloud_cover_high:                       "cloud_cover_high",
	Variablecloud_cover_low:                        "cloud_cover_low",
	Variablecloud_cover_mid:                        "cloud_cover_mid",
	Variabledaylight_duration:                      "daylight_duration",
	Variabledew_point:                              "dew_point",
	Variablediffuse_radiation:                      "diffuse_radiation",
	Variablediffuse_radiation_instant:              "diffuse_radiation_instant",
	Variabledirect_normal_irradiance:               "direct_normal_irradiance",
	Variabledirect_normal_irradiance_instant:       "direct_normal_irradiance_instant",
	Variabledirect_radiation:                       "direct_radiation",
	Variabledirect_radiation_instant:               "direct_radiation_instant",
	Variableet0_fao_evapotranspiration:             "et0_fao_evapotranspiration",
	Variableevapotranspiration:                     "evapotranspiration",
	Variablefreezing_level_height:                  "freezing_level_height",
	Variablegrowing_degree_days:                    "growing_degree_days",
	Variableis_day:                                 "is_day",
	Variablelatent_heat_flux:                       "latent_heat_flux",
	Variableleaf_wetness_probability:               "leaf_wetness_probability",
	Variablelifted_index:                           "lifted_index",
	Variablelightning_potential:                    "lightning_potential",
	Variableprecipitation:                          "precipitation",
	Variableprecipitation_hours:                    "precipitation_hours",
	Variableprecipitation_probability:              "precipitation_probability",
	Variablepressure_msl:                           "pressure_msl",
	Variablerain:                                   "rain",
	Variablerelative_humidity:                      "relative_humidity",
	Variablerunoff:                                 "runoff",
	Variablesensible_heat_flux:                     "sensible_heat_flux",
	Variableshortwave_radiation:                    "shortwave_radiation",
	Variableshortwave_radiation_instant:            "shortwave_radiation_instant",
	Variableshowers:                                "showers",
	Variablesnow_depth:                             "snow_depth",
	Variablesnow_height:                            "snow_height",
	Variablesnowfall:                               "snowfall",
	Variablesnowfall_height:                        "snowfall_height",
	Variablesnowfall_water_equivalent:              "snowfall_water_equivalent",
	Variablesunrise:                                "sunrise",
	Variablesunset:                                 "sunset",
	Variablesoil_moisture:                          "soil_moisture",
	Variablesoil_moisture_index:                    "soil_moisture_index",
	Variablesoil_temperature:                       "soil_temperature",
	Variablesurface_pressure:                       "surface_pressure",
	Variablesurface_temperature:                    "surface_temperature",
	Variabletemperature:                            "temperature",
	Variableterrestrial_radiation:                  "terrestrial_radiation",
	Variableterrestrial_radiation_instant:          "terrestrial_radiation_instant",
	Variabletotal_column_integrated_water_vapour:   "total_column_integrated_water_vapour",
	Variableupdraft:                                "updraft",
	Variableuv_index:                               "uv_index",
	Variableuv_index_clear_sky:                     "uv_index_clear_sky",
	Variablevapour_pressure_deficit:                "vapour_pressure_deficit",
	Variablevisibility:                             "visibility",
	Variableweather_code:                           "weather_code",
	Variablewind_direction:                         "wind_direction",
	Variablewind_gusts:                             "wind_gusts",
	Variablewind_speed:                             "wind_speed",
	Variablevertical_velocity:                      "vertical_velocity",
	Variablegeopotential_height:                    "geopotential_height",
	Variablewet_bulb_temperature:                   "wet_bulb_temperature",
	Variableriver_discharge:                        "river_discharge",
	Variablewave_height:                            "wave_height",
	Variablewave_period:                            "wave_period",
	Variablewave_direction:                         "wave_direction",
	Variablewind_wave_height:                       "wind_wave_height",
	Variablewind_wave_period:                       "wind_wave_period",
	Variablewind_wave_peak_period:                  "wind_wave_peak_period",
	Variablewind_wave_direction:                    "wind_wave_direction",
	Variableswell_wave_height:                      "swell_wave_height",
	Variableswell_wave_period:                      "swell_wave_period",
	Variableswell_wave_peak_period:                 "swell_wave_peak_period",
	Variableswell_wave_direction:                   "swell_wave_direction",
	Variablepm10:                                   "pm10",
	Variablepm2p5:                                  "pm2p5",
	Variabledust:                                   "dust",
	Variableaerosol_optical_depth:                  "aerosol_optical_depth",
	Variablecarbon_monoxide:                        "carbon_monoxide",
	Variablenitrogen_dioxide:                       "nitrogen_dioxide",
	Variableammonia:                                "ammonia",
	Variableozone:                                  "ozone",
	Variablesulphur_dioxide:                        "sulphur_dioxide",
	Variablealder_pollen:                           "alder_pollen",
	Variablebirch_pollen:                           "birch_pollen",
	Variablegrass_pollen:                           "grass_pollen",
	Variablemugwort_pollen:                         "mugwort_pollen",
	Variableolive_pollen:                           "olive_pollen",
	Variableragweed_pollen:                         "ragweed_pollen",
	Variableeuropean_aqi:                           "european_aqi",
	Variableeuropean_aqi_pm2p5:                     "european_aqi_pm2p5",
	Variableeuropean_aqi_pm10:                      "european_aqi_pm10",
	Variableeuropean_aqi_nitrogen_dioxide:          "european_aqi_nitrogen_dioxide",
	Variableeuropean_aqi_ozone:                     "european_aqi_ozone",
	Variableeuropean_aqi_sulphur_dioxide:           "european_aqi_sulphur_dioxide",
	Variableus_aqi:                                 "us_aqi",
	Variableus_aqi_pm2p5:                           "us_aqi_pm2p5",
	Variableus_aqi_pm10:                            "us_aqi_pm10",
	Variableus_aqi_nitrogen_dioxide:                "us_aqi_nitrogen_dioxide",
	Variableus_aqi_ozone:                           "us_aqi_ozone",
	Variableus_aqi_sulphur_dioxide:                 "us_aqi_sulphur_dioxide",
	Variableus_aqi_carbon_monoxide:                 "us_aqi_carbon_monoxide",
	Variablesunshine_duration:                      "sunshine_duration",
	Variableconvective_inhibition:                  "convective_inhibition",
	Variableshortwave_radiation_clear_sky:          "shortwave_radiation_clear_sky",
	Variableglobal_tilted_irradiance:               "global_tilted_irradiance",
	Variableglobal_tilted_irradiance_instant:       "global_tilted_irradiance_instant",
	Variableocean_current_velocity:                 "ocean_current_velocity",
	Variableocean_current_direction:                "ocean_current_direction",
	Variablecloud_base:                             "cloud_base",
	Variablecloud_top:                              "cloud_top",
	Variablemass_density:                           "mass_density",
	Variableboundary_layer_height:                  "boundary_layer_height",
	Variableformaldehyde:                           "formaldehyde",
	Variableglyoxal:                                "glyoxal",
	Variablenon_methane_volatile_organic_compounds: "non_methane_volatile_organic_compounds",
	Variablepm10_wildfires:                         "pm10_wildfires",
	Variableperoxyacyl_nitrates:                    "peroxyacyl_nitrates",
	Variablesecondary_inorganic_aerosol:            "secondary_inorganic_aerosol",
	Variableresidential_elementary_carbon:          "residential_elementary_carbon",
	Variabletotal_elementary_carbon:                "total_elementary_carbon",
	Variablepm2_5_total_organic_matter:             "pm2_5_total_organic_matter",
	Variablesea_salt_aerosol:                       "sea_salt_aerosol",
	Variablenitrogen_monoxide:                      "nitrogen_monoxide",
	Variablethunderstorm_probability:               "thunderstorm_probability",
	Variablerain_probability:                       "rain_probability",
	Variablefreezing_rain_probability:              "freezing_rain_probability",
	Variableice_pellets_probability:                "ice_pellets_probability",
	Variablesnowfall_probability:                   "snowfall_probability",
	Variablecarbon_dioxide:                         "carbon_dioxide",
	Variablemethane:                                "methane",
	Variablesea_level_height_msl:                   "sea_level_height_msl",
	Variablesea_surface_temperature:                "sea_surface_temperature",
	Variableinvert_barometer_height:                "invert_barometer_height",
	Variablehail:                                   "hail",
	Variablealbedo:                                 "albedo",
	Variableprecipitation_type:                     "precipitation_type",
	Variableconvective_cloud_base:                  "convective_cloud_base",
	Variableconvective_cloud_top:                   "convective_cloud_top",
	Variablesnow_depth_water_equivalent:            "snow_depth_water_equivalent",
	Variablesecondary_swell_wave_height:            "secondary_swell_wave_height",
	Variablesecondary_swell_wave_period:            "secondary_swell_wave_period",
	Variablesecondary_swell_wave_peak_period:       "secondary_swell_wave_peak_period",
	Variablesecondary_swell_wave_direction:         "secondary_swell_wave_direction",
	Variabletertiary_swell_wave_height:             "tertiary_swell_wave_height",
	Variabletertiary_swell_wave_period:             "tertiary_swell_wave_period",
	Variabletertiary_swell_wave_peak_period:        "tertiary_swell_wave_peak_period",
	Variabletertiary_swell_wave_direction:          "tertiary_swell_wave_direction",
	Variablewind_u_component:                       "wind_u_component",
	Variablewind_v_component:                       "wind_v_component",
	Variabletemperature_max24h:                     "temperature_max24h",
	Variabletemperature_min24h:                     "temperature_min24h",
	Variabletemperature_mean24h:                    "temperature_mean24h",
	Variablesnow_density:                           "snow_density",
	Variablelongwave_radiation:                     "longwave_radiation",
	Variablesea_ice_cover:                          "sea_ice_cover",
	Variablek_index:                                "k_index",
	Variableroughness_length:                       "roughness_length",
	Variablepotential_evapotranspiration:           "potential_evapotranspiration",
	Variablewave_peak_period:                       "wave_peak_period",
	Variabletemperature_max6h:                      "temperature_max6h",
	Variabletemperature_min6h:                      "temperature_min6h",
	Variablelightning_density:                      "lightning_density",
	Variablesea_ice_thickness:                      "sea_ice_thickness",
	Variableshortwave_radiation_clear_sky_instant:  "shortwave_radiation_clear_sky_instant",
	Variablesea_water_salinity:                     "sea_water_salinity",
	Variabletotal_column_water:                     "total_column_water",
	Variableair_density:                            "air_density",
	Variablemoonrise:                               "moonrise",
	Variablemoonset:                                "moonset",
	Variablemoon_phase:                             "moon_phase",
}

var EnumValuesVariable = map[string]Variable{
	"undefined":                              Variableundefined,
	"apparent_temperature":                   Variableapparent_temperature,
	"cape":                                   Variablecape,
	"cloud_cover":                            Variablecloud_cover,
	"cloud_cover_high":                       Variablecloud_cover_high,
	"cloud_cover_low":                        Variablecloud_cover_low,
	"cloud_cover_mid":                        Variablecloud_cover_mid,
	"daylight_duration":                      Variabledaylight_duration,
	"dew_point":                              Variabledew_point,
	"diffuse_radiation":                      Variablediffuse_radiation,
	"diffuse_radiation_instant":              Variablediffuse_radiation_instant,
	"direct_normal_irradiance":               Variabledirect_normal_irradiance,
	"direct_normal_irradiance_instant":       Variabledirect_normal_irradiance_instant,
	"direct_radiation":                       Variabledirect_radiation,
	"direct_radiation_instant":               Variabledirect_radiation_instant,
	"et0_fao_evapotranspiration":             Variableet0_fao_evapotranspiration,
	"evapotranspiration":                     Variableevapotranspiration,
	"freezing_level_height":                  Variablefreezing_level_height,
	"growing_degree_days":                    Variablegrowing_degree_days,
	"is_day":                                 Variableis_day,
	"latent_heat_flux":                       Variablelatent_heat_flux,
	"leaf_wetness_probability":               Variableleaf_wetness_probability,
	"lifted_index":                           Variablelifted_index,
	"lightning_potential":                    Variablelightning_potential,
	"precipitation":                          Variableprecipitation,
	"precipitation_hours":                    Variableprecipitation_hours,
	"precipitation_probability":              Variableprecipitation_probability,
	"pressure_msl":                           Variablepressure_msl,
	"rain":                                   Variablerain,
	"relative_humidity":                      Variablerelative_humidity,
	"runoff":                                 Variablerunoff,
	"sensible_heat_flux":                     Variablesensible_heat_flux,
	"shortwave_radiation":                    Variableshortwave_radiation,
	"shortwave_radiation_instant":            Variableshortwave_radiation_instant,
	"showers":                                Variableshowers,
	"snow_depth":                             Variablesnow_depth,
	"snow_height":                            Variablesnow_height,
	"snowfall":                               Variablesnowfall,
	"snowfall_height":                        Variablesnowfall_height,
	"snowfall_water_equivalent":              Variablesnowfall_water_equivalent,
	"sunrise":                                Variablesunrise,
	"sunset":                                 Variablesunset,
	"soil_moisture":                          Variablesoil_moisture,
	"soil_moisture_index":                    Variablesoil_moisture_index,
	"soil_temperature":                       Variablesoil_temperature,
	"surface_pressure":                       Variablesurface_pressure,
	"surface_temperature":                    Variablesurface_temperature,
	"temperature":                            Variabletemperature,
	"terrestrial_radiation":                  Variableterrestrial_radiation,
	"terrestrial_radiation_instant":          Variableterrestrial_radiation_instant,
	"total_column_integrated_water_vapour":   Variabletotal_column_integrated_water_vapour,
	"updraft":                                Variableupdraft,
	"uv_index":                               Variableuv_index,
	"uv_index_clear_sky":                     Variableuv_index_clear_sky,
	"vapour_pressure_deficit":                Variablevapour_pressure_deficit,
	"visibility":                             Variablevisibility,
	"weather_code":                           Variableweather_code,
	"wind_direction":                         Variablewind_direction,
	"wind_gusts":                             Variablewind_gusts,
	"wind_speed":                             Variablewind_speed,
	"vertical_velocity":                      Variablevertical_velocity,
	"geopotential_height":                    Variablegeopotential_height,
	"wet_bulb_temperature":                   Variablewet_bulb_temperature,
	"river_discharge":                        Variableriver_discharge,
	"wave_height":                            Variablewave_height,
	"wave_period":                            Variablewave_period,
	"wave_direction":                         Variablewave_direction,
	"wind_wave_height":                       Variablewind_wave_height,
	"wind_wave_period":                       Variablewind_wave_period,
	"wind_wave_peak_period":                  Variablewind_wave_peak_period,
	"wind_wave_direction":                    Variablewind_wave_direction,
	"swell_wave_height":                      Variableswell_wave_height,
	"swell_wave_period":                      Variableswell_wave_period,
	"swell_wave_peak_period":                 Variableswell_wave_peak_period,
	"swell_wave_direction":                   Variableswell_wave_direction,
	"pm10":                                   Variablepm10,
	"pm2p5":                                  Variablepm2p5,
	"dust":                                   Variabledust,
	"aerosol_optical_depth":                  Variableaerosol_optical_depth,
	"carbon_monoxide":                        Variablecarbon_monoxide,
	"nitrogen_dioxide":                       Variablenitrogen_dioxide,
	"ammonia":                                Variableammonia,
	"ozone":                                  Variableozone,
	"sulphur_dioxide":                        Variablesulphur_dioxide,
	"alder_pollen":                           Variablealder_pollen,
	"birch_pollen":                           Variablebirch_pollen,
	"grass_pollen":                           Variablegrass_pollen,
	"mugwort_pollen":                         Variablemugwort_pollen,
	"olive_pollen":                           Variableolive_pollen,
	"ragweed_pollen":                         Variableragweed_pollen,
	"european_aqi":                           Variableeuropean_aqi,
	"european_aqi_pm2p5":                     Variableeuropean_aqi_pm2p5,
	"european_aqi_pm10":                      Variableeuropean_aqi_pm10,
	"european_aqi_nitrogen_dioxide":          Variableeuropean_aqi_nitrogen_dioxide,
	"european_aqi_ozone":                     Variableeuropean_aqi_ozone,
	"european_aqi_sulphur_dioxide":           Variableeuropean_aqi_sulphur_dioxide,
	"us_aqi":                                 Variableus_aqi,
	"us_aqi_pm2p5":                           Variableus_aqi_pm2p5,
	"us_aqi_pm10":                            Variableus_aqi_pm10,
	"us_aqi_nitrogen_dioxide":                Variableus_aqi_nitrogen_dioxide,
	"us_aqi_ozone":                           Variableus_aqi_ozone,
	"us_aqi_sulphur_dioxide":                 Variableus_aqi_sulphur_dioxide,
	"us_aqi_carbon_monoxide":                 Variableus_aqi_carbon_monoxide,
	"sunshine_duration":                      Variablesunshine_duration,
	"convective_inhibition":                  Variableconvective_inhibition,
	"shortwave_radiation_clear_sky":          Variableshortwave_radiation_clear_sky,
	"global_tilted_irradiance":               Variableglobal_tilted_irradiance,
	"global_tilted_irradiance_instant":       Variableglobal_tilted_irradiance_instant,
	"ocean_current_velocity":                 Variableocean_current_velocity,
	"ocean_current_direction":                Variableocean_current_direction,
	"cloud_base":                             Variablecloud_base,
	"cloud_top":                              Variablecloud_top,
	"mass_density":                           Variablemass_density,
	"boundary_layer_height":                  Variableboundary_layer_height,
	"formaldehyde":                           Variableformaldehyde,
	"glyoxal":                                Variableglyoxal,
	"non_methane_volatile_organic_compounds": Variablenon_methane_volatile_organic_compounds,
	"pm10_wildfires":                         Variablepm10_wildfires,
	"peroxyacyl_nitrates":                    Variableperoxyacyl_nitrates,
	"secondary_inorganic_aerosol":            Variablesecondary_inorganic_aerosol,
	"residential_elementary_carbon":          Variableresidential_elementary_carbon,
	"total_elementary_carbon":                Variabletotal_elementary_carbon,
	"pm2_5_total_organic_matter":             Variablepm2_5_total_organic_matter,
	"sea_salt_aerosol":                       Variablesea_salt_aerosol,
	"nitrogen_monoxide":                      Variablenitrogen_monoxide,
	"thunderstorm_probability":               Variablethunderstorm_probability,
	"rain_probability":                       Variablerain_probability,
	"freezing_rain_probability":              Variablefreezing_rain_probability,
	"ice_pellets_probability":                Variableice_pellets_probability,
	"snowfall_probability":                   Variablesnowfall_probability,
	"carbon_dioxide":                         Variablecarbon_dioxide,
	"methane":                                Variablemethane,
	"sea_level_height_msl":                   Variablesea_level_height_msl,
	"sea_surface_temperature":                Variablesea_surface_temperature,
	"invert_barometer_height":                Variableinvert_barometer_height,
	"hail":                                   Variablehail,
	"albedo":                                 Variablealbedo,
	"precipitation_type":                     Variableprecipitation_type,
	"convective_cloud_base":                  Variableconvective_cloud_base,
	"convective_cloud_top":                   Variableconvective_cloud_top,
	"snow_depth_water_equivalent":            Variablesnow_depth_water_equivalent,
	"secondary_swell_wave_height":            Variablesecondary_swell_wave_height,
	"secondary_swell_wave_period":            Variablesecondary_swell_wave_period,
	"secondary_swell_wave_peak_period":       Variablesecondary_swell_wave_peak_period,
	"secondary_swell_wave_direction":         Variablesecondary_swell_wave_direction,
	"tertiary_swell_wave_height":             Variabletertiary_swell_wave_height,
	"tertiary_swell_wave_period":             Variabletertiary_swell_wave_period,
	"tertiary_swell_wave_peak_period":        Variabletertiary_swell_wave_peak_period,
	"tertiary_swell_wave_direction":          Variabletertiary_swell_wave_direction,
	"wind_u_component":                       Variablewind_u_component,
	"wind_v_component":                       Variablewind_v_component,
	"temperature_max24h":                     Variabletemperature_max24h,
	"temperature_min24h":                     Variabletemperature_min24h,
	"temperature_mean24h":                    Variabletemperature_mean24h,
	"snow_density":                           Variablesnow_density,
	"longwave_radiation":                     Variablelongwave_radiation,
	"sea_ice_cover":                          Variablesea_ice_cover,
	"k_index":                                Variablek_index,
	"roughness_length":                       Variableroughness_length,
	"potential_evapotranspiration":           Variablepotential_evapotranspiration,
	"wave_peak_period":                       Variablewave_peak_period,
	"temperature_max6h":                      Variabletemperature_max6h,
	"temperature_min6h":                      Variabletemperature_min6h,
	"lightning_density":                      Variablelightning_density,
	"sea_ice_thickness":                      Variablesea_ice_thickness,
	"shortwave_radiation_clear_sky_instant":  Variableshortwave_radiation_clear_sky_instant,
	"sea_water_salinity":                     Variablesea_water_salinity,
	"total_column_water":                     Variabletotal_column_water,
	"air_density":                            Variableair_density,
	"moonrise":                               Variablemoonrise,
	"moonset":                                Variablemoonset,
	"moon_phase":                             Variablemoon_phase,
}

func (v Variable) String() string {
	if s, ok := EnumNamesVariable[v]; ok {
		return s
	}
	return "Variable(" + strconv.FormatInt(int64(v), 10) + ")"
}

type Aggregation byte

const (
	Aggregationnone     Aggregation = 0
	Aggregationminimum  Aggregation = 1
	Aggregationmaximum  Aggregation = 2
	Aggregationmean     Aggregation = 3
	Aggregationp10      Aggregation = 4
	Aggregationp25      Aggregation = 5
	Aggregationmedian   Aggregation = 6
	Aggregationp75      Aggregation = 7
	Aggregationp90      Aggregation = 8
	Aggregationdominant Aggregation = 9
	Aggregationsum      Aggregation = 10
	Aggregationspread   Aggregation = 11
	Aggregationanomaly  Aggregation = 12
	Aggregationsot10    Aggregation = 13
	Aggregationsot90    Aggregation = 14
	Aggregationefi      Aggregation = 15
)

var EnumNamesAggregation = map[Aggregation]string{
	Aggregationnone:     "none",
	Aggregationminimum:  "minimum",
	Aggregationmaximum:  "maximum",
	Aggregationmean:     "mean",
	Aggregationp10:      "p10",
	Aggregationp25:      "p25",
	Aggregationmedian:   "median",
	Aggregationp75:      "p75",
	Aggregationp90:      "p90",
	Aggregationdominant: "dominant",
	Aggregationsum:      "sum",
	Aggregationspread:   "spread",
	Aggregationanomaly:  "anomaly",
	Aggregationsot10:    "sot10",
	Aggregationsot90:    "sot90",
	Aggregationefi:      "efi",
}

var EnumValuesAggregation = map[string]Aggregation{
	"none":     Aggregationnone,
	"minimum":  Aggregationminimum,
	"maximum":  Aggregationmaximum,
	"mean":     Aggregationmean,
	"p10":      Aggregationp10,
	"p25":      Aggregationp25,
	"median":   Aggregationmedian,
	"p75":      Aggregationp75,
	"p90":      Aggregationp90,
	"dominant": Aggregationdominant,
	"sum":      Aggregationsum,
	"spread":   Aggregationspread,
	"anomaly":  Aggregationanomaly,
	"sot10":    Aggregationsot10,
	"sot90":    Aggregationsot90,
	"efi":      Aggregationefi,
}

func (v Aggregation) String() string {
	if s, ok := EnumNamesAggregation[v]; ok {
		return s
	}
	return "Aggregation(" + strconv.FormatInt(int64(v), 10) + ")"
}

type Probability byte

const (
	Probabilitynone       Probability = 0
	Probabilitygt0        Probability = 1
	Probabilitygt0p1      Probability = 2
	Probabilitygt1        Probability = 3
	Probabilitygt2        Probability = 4
	Probabilitygt3        Probability = 5
	Probabilitygt4        Probability = 6
	Probabilitygt5        Probability = 7
	Probabilitygt8        Probability = 8
	Probabilitygt10       Probability = 9
	Probabilitygt15       Probability = 10
	Probabilitygt20       Probability = 11
	Probabilitygt25       Probability = 12
	Probabilitygt30       Probability = 13
	Probabilitygt35       Probability = 14
	Probabilitygt40       Probability = 15
	Probabilitygt50       Probability = 16
	Probabilitygt60       Probability = 17
	Probabilitygt75       Probability = 18
	Probabilitygt80       Probability = 19
	Probabilitygt100      Probability = 20
	Probabilitylt0        Probability = 21
	Probabilitylt0p1      Probability = 22
	Probabilitylt1        Probability = 23
	Probabilityltm1       Probability = 24
	Probabilityltm2       Probability = 25
	Probabilityltm3       Probability = 26
	Probabilityltm4       Probability = 27
	Probabilityltm5       Probability = 28
	Probabilityltm8       Probability = 29
	Probabilityltm10      Probability = 30
	Probabilityltm15      Probability = 31
	Probabilityltm20      Probability = 32
	Probabilitygt1stdev   Probability = 33
	Probabilitygt1p5stdev Probability = 34
	Probabilitygt2stdev   Probability = 35
	Probabilitylt1stdev   Probability = 36
	Probabilitylt1p5stdev Probability = 37
	Probabilitylt2stdev   Probability = 38
)

var EnumNamesProbability = map[Probability]string{
	Probabilitynone:       "none",
	Probabilitygt0:        "gt0",
	Probabilitygt0p1:      "gt0p1",
	Probabilitygt1:        "gt1",
	Probabilitygt2:        "gt2",
	Probabilitygt3:        "gt3",
	Probabilitygt4:        "gt4",
	Probabilitygt5:        "gt5",
	Probabilitygt8:        "gt8",
	Probabilitygt10:       "gt10",
	Probabilitygt15:       "gt15",
	Probabilitygt20:       "gt20",
	Probabilitygt25:       "gt25",
	Probabilitygt30:       "gt30",
	Probabilitygt35:       "gt35",
	Probabilitygt40:       "gt40",
	Probabilitygt50:       "gt50",
	Probabilitygt60:       "gt60",
	Probabilitygt75:       "gt75",
	Probabilitygt80:       "gt80",
	Probabilitygt100:      "gt100",
	Probabilitylt0:        "lt0",
	Probabilitylt0p1:      "lt0p1",
	Probabilitylt1:        "lt1",
	Probabilityltm1:       "ltm1",
	Probabilityltm2:       "ltm2",
	Probabilityltm3:       "ltm3",
	Probabilityltm4:       "ltm4",
	Probabilityltm5:       "ltm5",
	Probabilityltm8:       "ltm8",
	Probabilityltm10:      "ltm10",
	Probabilityltm15:      "ltm15",
	Probabilityltm20:      "ltm20",
	Probabilitygt1stdev:   "gt1stdev",
	Probabilitygt1p5stdev: "gt1p5stdev",
	Probabilitygt2stdev:   "gt2stdev",
	Probabilitylt1stdev:   "lt1stdev",
	Probabilitylt1p5stdev: "lt1p5stdev",
	Probabilitylt2stdev:   "lt2stdev",
}

var EnumValuesProbability = map[string]Probability{
	"none":       Probabilitynone,
	"gt0":        Probabilitygt0,
	"gt0p1":      Probabilitygt0p1,
	"gt1":        Probabilitygt1,
	"gt2":        Probabilitygt2,
	"gt3":        Probabilitygt3,
	"gt4":        Probabilitygt4,
	"gt5":        Probabilitygt5,
	"gt8":        Probabilitygt8,
	"gt10":       Probabilitygt10,
	"gt15":       Probabilitygt15,
	"gt20":       Probabilitygt20,
	"gt25":       Probabilitygt25,
	"gt30":       Probabilitygt30,
	"gt35":       Probabilitygt35,
	"gt40":       Probabilitygt40,
	"gt50":       Probabilitygt50,
	"gt60":       Probabilitygt60,
	"gt75":       Probabilitygt75,
	"gt80":       Probabilitygt80,
	"gt100":      Probabilitygt100,
	"lt0":        Probabilitylt0,
	"lt0p1":      Probabilitylt0p1,
	"lt1":        Probabilitylt1,
	"ltm1":       Probabilityltm1,
	"ltm2":       Probabilityltm2,
	"ltm3":       Probabilityltm3,
	"ltm4":       Probabilityltm4,
	"ltm5":       Probabilityltm5,
	"ltm8":       Probabilityltm8,
	"ltm10":      Probabilityltm10,
	"ltm15":      Probabilityltm15,
	"ltm20":      Probabilityltm20,
	"gt1stdev":   Probabilitygt1stdev,
	"gt1p5stdev": Probabilitygt1p5stdev,
	"gt2stdev":   Probabilitygt2stdev,
	"lt1stdev":   Probabilitylt1stdev,
	"lt1p5stdev": Probabilitylt1p5stdev,
	"lt2stdev":   Probabilitylt2stdev,
}

func (v Probability) String() string {
	if s, ok := EnumNamesProbability[v]; ok {
		return s
	}
	return "Probability(" + strconv.FormatInt(int64(v), 10) + ")"
}

type VariableWithValues struct {
	_tab flatbuffers.Table
}

func GetRootAsVariableWithValues(buf []byte, offset flatbuffers.UOffsetT) *VariableWithValues {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VariableWithValues{}
	x.Init(buf, n+offset)
	return x
}

func FinishVariableWithValuesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVariableWithValues(buf []byte, offset flatbuffers.UOffsetT) *VariableWithValues {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VariableWithValues{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVariableWithValuesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VariableWithValues) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VariableWithValues) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VariableWithValues) Variable() Variable {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Variable(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VariableWithValues) MutateVariable(n Variable) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *VariableWithValues) Unit() Unit {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Unit(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VariableWithValues) MutateUnit(n Unit) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *VariableWithValues) Value() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *VariableWithValues) MutateValue(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *VariableWithValues) Values(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *VariableWithValues) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *VariableWithValues) MutateValues(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *VariableWithValues) ValuesInt64(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *VariableWithValues) ValuesInt64Length() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *VariableWithValues) MutateValuesInt64(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *VariableWithValues) Altitude() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariableWithValues) MutateAltitude(n int16) bool {
	return rcv._tab.MutateInt16Slot(14, n)
}

func (rcv *VariableWithValues) Aggregation() Aggregation {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return Aggregation(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VariableWithValues) MutateAggregation(n Aggregation) bool {
	return rcv._tab.MutateByteSlot(16, byte(n))
}

func (rcv *VariableWithValues) PressureLevel() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariableWithValues) MutatePressureLevel(n int16) bool {
	return rcv._tab.MutateInt16Slot(18, n)
}

func (rcv *VariableWithValues) Depth() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariableWithValues) MutateDepth(n int16) bool {
	return rcv._tab.MutateInt16Slot(20, n)
}

func (rcv *VariableWithValues) DepthTo() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariableWithValues) MutateDepthTo(n int16) bool {
	return rcv._tab.MutateInt16Slot(22, n)
}

func (rcv *VariableWithValues) EnsembleMember() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariableWithValues) MutateEnsembleMember(n int16) bool {
	return rcv._tab.MutateInt16Slot(24, n)
}

func (rcv *VariableWithValues) PreviousDay() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariableWithValues) MutatePreviousDay(n int16) bool {
	return rcv._tab.MutateInt16Slot(26, n)
}

func (rcv *VariableWithValues) Probability() Probability {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return Probability(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VariableWithValues) MutateProbability(n Probability) bool {
	return rcv._tab.MutateByteSlot(28, byte(n))
}

func VariableWithValuesStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func VariableWithValuesAddVariable(builder *flatbuffers.Builder, variable Variable) {
	builder.PrependByteSlot(0, byte(variable), 0)
}
func VariableWithValuesAddUnit(builder *flatbuffers.Builder, unit Unit) {
	builder.PrependByteSlot(1, byte(unit), 0)
}
func VariableWithValuesAddValue(builder *flatbuffers.Builder, value float32) {
	builder.PrependFloat32Slot(2, value, 0.0)
}
func VariableWithValuesAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(values), 0)
}
func VariableWithValuesStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func VariableWithValuesAddValuesInt64(builder *flatbuffers.Builder, valuesInt64 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(valuesInt64), 0)
}
func VariableWithValuesStartValuesInt64Vector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func VariableWithValuesAddAltitude(builder *flatbuffers.Builder, altitude int16) {
	builder.PrependInt16Slot(5, altitude, 0)
}
func VariableWithValuesAddAggregation(builder *flatbuffers.Builder, aggregation Aggregation) {
	builder.PrependByteSlot(6, byte(aggregation), 0)
}
func VariableWithValuesAddPressureLevel(builder *flatbuffers.Builder, pressureLevel int16) {
	builder.PrependInt16Slot(7, pressureLevel, 0)
}
func VariableWithValuesAddDepth(builder *flatbuffers.Builder, depth int16) {
	builder.PrependInt16Slot(8, depth, 0)
}
func VariableWithValuesAddDepthTo(builder *flatbuffers.Builder, depthTo int16) {
	builder.PrependInt16Slot(9, depthTo, 0)
}
func VariableWithValuesAddEnsembleMember(builder *flatbuffers.Builder, ensembleMember int16) {
	builder.PrependInt16Slot(10, ensembleMember, 0)
}
func VariableWithValuesAddPreviousDay(builder *flatbuffers.Builder, previousDay int16) {
	builder.PrependInt16Slot(11, previousDay, 0)
}
func VariableWithValuesAddProbability(builder *flatbuffers.Builder, probability Probability) {
	builder.PrependByteSlot(12, byte(probability), 0)
}
func VariableWithValuesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type VariablesWithTime struct {
	_tab flatbuffers.Table
}

func GetRootAsVariablesWithTime(buf []byte, offset flatbuffers.UOffsetT) *VariablesWithTime {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VariablesWithTime{}
	x.Init(buf, n+offset)
	return x
}

func FinishVariablesWithTimeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVariablesWithTime(buf []byte, offset flatbuffers.UOffsetT) *VariablesWithTime {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VariablesWithTime{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVariablesWithTimeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VariablesWithTime) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VariablesWithTime) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VariablesWithTime) Time() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariablesWithTime) MutateTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *VariablesWithTime) TimeEnd() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariablesWithTime) MutateTimeEnd(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *VariablesWithTime) Interval() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariablesWithTime) MutateInterval(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *VariablesWithTime) Variables(obj *VariableWithValues, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *VariablesWithTime) VariablesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func VariablesWithTimeStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func VariablesWithTimeAddTime(builder *flatbuffers.Builder, time int64) {
	builder.PrependInt64Slot(0, time, 0)
}
func VariablesWithTimeAddTimeEnd(builder *flatbuffers.Builder, timeEnd int64) {
	builder.PrependInt64Slot(1, timeEnd, 0)
}
func VariablesWithTimeAddInterval(builder *flatbuffers.Builder, interval int32) {
	builder.PrependInt32Slot(2, interval, 0)
}
func VariablesWithTimeAddVariables(builder *flatbuffers.Builder, variables flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(variables), 0)
}
func VariablesWithTimeStartVariablesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func VariablesWithTimeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type VariablesWithMonth struct {
	_tab flatbuffers.Table
}

func GetRootAsVariablesWithMonth(buf []byte, offset flatbuffers.UOffsetT) *VariablesWithMonth {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VariablesWithMonth{}
	x.Init(buf, n+offset)
	return x
}

func FinishVariablesWithMonthBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVariablesWithMonth(buf []byte, offset flatbuffers.UOffsetT) *VariablesWithMonth {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VariablesWithMonth{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVariablesWithMonthBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VariablesWithMonth) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VariablesWithMonth) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VariablesWithMonth) Year() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariablesWithMonth) MutateYear(n int16) bool {
	return rcv._tab.MutateInt16Slot(4, n)
}

func (rcv *VariablesWithMonth) Month() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariablesWithMonth) MutateMonth(n int8) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func (rcv *VariablesWithMonth) Count() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VariablesWithMonth) MutateCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *VariablesWithMonth) Variables(obj *VariableWithValues, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *VariablesWithMonth) VariablesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func VariablesWithMonthStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func VariablesWithMonthAddYear(builder *flatbuffers.Builder, year int16) {
	builder.PrependInt16Slot(0, year, 0)
}
func VariablesWithMonthAddMonth(builder *flatbuffers.Builder, month int8) {
	builder.PrependInt8Slot(1, month, 0)
}
func VariablesWithMonthAddCount(builder *flatbuffers.Builder, count int32) {
	builder.PrependInt32Slot(2, count, 0)
}
func VariablesWithMonthAddVariables(builder *flatbuffers.Builder, variables flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(variables), 0)
}
func VariablesWithMonthStartVariablesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func VariablesWithMonthEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type WeatherApiResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsWeatherApiResponse(buf []byte, offset flatbuffers.UOffsetT) *WeatherApiResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WeatherApiResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishWeatherApiResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWeatherApiResponse(buf []byte, offset flatbuffers.UOffsetT) *WeatherApiResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WeatherApiResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWeatherApiResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *WeatherApiResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WeatherApiResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WeatherApiResponse) Latitude() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *WeatherApiResponse) MutateLatitude(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *WeatherApiResponse) Longitude() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *WeatherApiResponse) MutateLongitude(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *WeatherApiResponse) Elevation() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *WeatherApiResponse) MutateElevation(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *WeatherApiResponse) GenerationTimeMilliseconds() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *WeatherApiResponse) MutateGenerationTimeMilliseconds(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *WeatherApiResponse) LocationId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *WeatherApiResponse) MutateLocationId(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *WeatherApiResponse) Model() Model {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return Model(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *WeatherApiResponse) MutateModel(n Model) bool {
	return rcv._tab.MutateByteSlot(14, byte(n))
}

func (rcv *WeatherApiResponse) UtcOffsetSeconds() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *WeatherApiResponse) MutateUtcOffsetSeconds(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *WeatherApiResponse) Timezone() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WeatherApiResponse) TimezoneAbbreviation() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WeatherApiResponse) Current(obj *VariablesWithTime) *VariablesWithTime {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VariablesWithTime)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WeatherApiResponse) Daily(obj *VariablesWithTime) *VariablesWithTime {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VariablesWithTime)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WeatherApiResponse) Hourly(obj *VariablesWithTime) *VariablesWithTime {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VariablesWithTime)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WeatherApiResponse) Minutely15(obj *VariablesWithTime) *VariablesWithTime {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VariablesWithTime)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WeatherApiResponse) Monthly(obj *VariablesWithMonth) *VariablesWithMonth {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VariablesWithMonth)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *WeatherApiResponse) Weekly(obj *VariablesWithTime) *VariablesWithTime {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VariablesWithTime)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func WeatherApiResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func WeatherApiResponseAddLatitude(builder *flatbuffers.Builder, latitude float32) {
	builder.PrependFloat32Slot(0, latitude, 0.0)
}
func WeatherApiResponseAddLongitude(builder *flatbuffers.Builder, longitude float32) {
	builder.PrependFloat32Slot(1, longitude, 0.0)
}
func WeatherApiResponseAddElevation(builder *flatbuffers.Builder, elevation float32) {
	builder.PrependFloat32Slot(2, elevation, 0.0)
}
func WeatherApiResponseAddGenerationTimeMilliseconds(builder *flatbuffers.Builder, generationTimeMilliseconds float32) {
	builder.PrependFloat32Slot(3, generationTimeMilliseconds, 0.0)
}
func WeatherApiResponseAddLocationId(builder *flatbuffers.Builder, locationId int64) {
	builder.PrependInt64Slot(4, locationId, 0)
}
func WeatherApiResponseAddModel(builder *flatbuffers.Builder, model Model) {
	builder.PrependByteSlot(5, byte(model), 0)
}
func WeatherApiResponseAddUtcOffsetSeconds(builder *flatbuffers.Builder, utcOffsetSeconds int32) {
	builder.PrependInt32Slot(6, utcOffsetSeconds, 0)
}
func WeatherApiResponseAddTimezone(builder *flatbuffers.Builder, timezone flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(timezone), 0)
}
func WeatherApiResponseAddTimezoneAbbreviation(builder *flatbuffers.Builder, timezoneAbbreviation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(timezoneAbbreviation), 0)
}
func WeatherApiResponseAddCurrent(builder *flatbuffers.Builder, current flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(current), 0)
}
func WeatherApiResponseAddDaily(builder *flatbuffers.Builder, daily flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(daily), 0)
}
func WeatherApiResponseAddHourly(builder *flatbuffers.Builder, hourly flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(hourly), 0)
}
func WeatherApiResponseAddMinutely15(builder *flatbuffers.Builder, minutely15 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(minutely15), 0)
}
func WeatherApiResponseAddMonthly(builder *flatbuffers.Builder, monthly flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(monthly), 0)
}
func WeatherApiResponseAddWeekly(builder *flatbuffers.Builder, weekly flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(weekly), 0)
}
func WeatherApiResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
